### ISSUE TITLE
at() live property

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#103]
Hi Andrew,

I found myself confused by the behaviour of the live property `at()` today. The calculation reconstructs the range of x values of an array, based on the `plot_x0()` and `plot_xdelta()` methods:
https://github.com/pynbody/tangos/blob/2f2039d13709b719ca853c0aa1ba93622af111cf/tangos/properties/live_profiles.py#L13-L20

However, it then assumes that the x value are linearly spaced by xdelta to locate the value in the array. This assumptions holds for the tangos builtins properties but not necessarily for some of custom defined properties which have e.g. logarithmic spacing in radius.

For my custom properties, I override the `plot_x_values()` method to ensure that plots are generated with the correct x range, here in the base class:
https://github.com/pynbody/tangos/blob/2f2039d13709b719ca853c0aa1ba93622af111cf/tangos/properties/__init__.py#L166-L169

Since this latter method is a public method of the `PropertyCalculation` class, wouldn't it make sense for the `at()` method to use `plot_x_values` directly rather than generating it?

Martin

**Comment by apontzen** [comment]
I agree it's inconsistent.

I suspect the best way to solve it is to put the at() interpolation logic into the properties class, so that it can be overridden alongside `plot_x_values`.

**Comment by apontzen** [comment]
I can't remember why this isn't closed -- given #11 is merged, shall I now close it @Martin-Rey ?

**Comment by Martin-Rey** [comment]
Yep it's fixed now
