### ISSUE TITLE
Missing last halo of HOP catalogue

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#108]
Hi,

It is not entirely clear to me whether this is a Pynbody or Tangos issue, but I'll open it here anyway.

I just noticed that Tangos is consistently missing the last halo of the RAMSES+HOP catalogue. I tracked it to an inconsistency between the `len()` method applied on Pynbody halo catalogues and their actual index structure. 

The following notebook is an example showing that the length of the catalogue returns 1825, but that halo indices run from 0 to 1825 (hence a length of 1826):

```
In [28]: s = pynbody.load("./output_00009/")

In [29]: h = s.halos()

In [30]: len(h)
Out[30]: 1825

In [31]: h[1825]
Out[31]: <SimSnap "./output_00009/:halo_1825" len=37>

In [32]: h[1824]
Out[32]: <SimSnap "./output_00009/:halo_1824" len=39>

In [33]: h[1826]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-f44840f7f2aa> in <module>()
----> 1 h[1826]

/scratch/dp101/shared/python/anaconda2/lib/python2.7/site-packages/pynbody-0.47-py2.7-linux-x86_64.egg/pynbody/halo/__init__.pyc in __getitem__(self, item)
     99             return res
    100         else:
--> 101             return self.calc_item(item)
    102 
    103     @property

/scratch/dp101/shared/python/anaconda2/lib/python2.7/site-packages/pynbody-0.47-py2.7-linux-x86_64.egg/pynbody/halo/__init__.pyc in calc_item(self, i)
     82                 return self._halos[i]
     83         else:
---> 84             h = self._get_halo(i)
     85             self._halos[i] = h  # weakref.ref(h)
     86             return h

/scratch/dp101/shared/python/anaconda2/lib/python2.7/site-packages/pynbody-0.47-py2.7-linux-x86_64.egg/pynbody/halo/__init__.pyc in _get_halo(self, i)
    245         x = Halo(i, self, self.base, self._get_halo_indices(i))
    246         if len(x) == 0:
--> 247             raise ValueError("Halo %s does not exist" % (str(i)))
    248         x._descriptor = "halo_" + str(i)
    249         return x

ValueError: Halo 1826 does not exist
```

When enumerating the halo catalogue with the pynbody handler here:
https://github.com/pynbody/tangos/blob/48e134a20d3bf1a8da1e3166c598233e28e5a822/tangos/input_handlers/pynbody.py#L236-L242
the range loop caps one index before the last and Tangos ends up missing the last halo.

It feels to me that evaluating len(halo_catalogue) with pynbody should return one more than the last index. However, it might be easier to adapt the Tangos loop to this issue in order to avoid breaking people's legacy code.

Hope this is clear,
Martin

**Comment by apontzen** [comment]
I think it's a bug in pynbody and should be fixed there, despite the risk of breaking code. If people have encountered the bug and worked around it, they can probably work around finding it fixed.
