### ISSUE TITLE
TypeError in add_bh.py:scan_for_BHs()

### ISSUE THREAD

**Issue by trquinn** [pynbody/tangos#113]
I get the following error when running "tangos_add_bh":
File "/home/u14266/.local/lib/python2.7/site-packages/tangos/scripts/add_bh.py", line 119, in scan_for_BHs
    bh_halos = bh_halos[bh_order_by_mass]
TypeError: 'NoneType' object has no attribute '__getitem__'

Later in the scan_for_BHs() function there is a test  "bh_halos is not None", so I assume that "None" is a valid return from bh_halo_assign().  Hence, it seems there should be a test for "bh_halos is not None on line 119.

**Comment by apontzen** [comment]
Yes reading the code I agree. Could you provide the context in which this actually arose? I am trying to find a test that will highlight it.

**Comment by trquinn** [comment]
The context is creating a database for a Romulus resolution simulation of a group (few times 10^13 Msun DM mass).  Here are the messages leading up to it:
sqlite:////home/u14266/scratch/tangos/sqlite.db
sqlite:////home/u14266/scratch/tangos/sqlite.db
sqlite:////home/u14266/scratch/tangos/sqlite.db
sqlite:////home/u14266/scratch/tangos/sqlite.db
[  0] 2020-02-12 17:09:00,972 : Send job 0 of 121 to node 1
[  0] 2020-02-12 17:09:00,972 : Send job 1 of 121 to node 2
[  0] 2020-02-12 17:09:00,972 : Send job 2 of 121 to node 3
[  1] 2020-02-12 17:09:00,972 : Processing <TimeStep u'h82651gs/h82651gs.000051' z=19.83 t=0.18 Gyr>
[  2] 2020-02-12 17:09:00,972 : Processing <TimeStep u'h82651gs/h82651gs.000054' z=19.09 t=0.19 Gyr>
[  3] 2020-02-12 17:09:00,972 : Processing <TimeStep u'h82651gs/h82651gs.000057' z=18.42 t=0.20 Gyr>
[  1] 2020-02-12 17:09:01,505 : Gathering existing BH halo information from database for step <TimeStep u'h82651gs/h82651gs.000051' z=19.83 t=0.18 Gyr>
[  3] 2020-02-12 17:09:01,505 : Gathering existing BH halo information from database for step <TimeStep u'h82651gs/h82651gs.000057' z=18.42 t=0.20 Gyr>
[  1] 2020-02-12 17:09:01,570 : ...found 0 existing BHs
[  3] 2020-02-12 17:09:01,570 : ...found 0 existing BHs
[  1] 2020-02-12 17:09:01,570 : Gathering BH info from simulation for step <TimeStep u'h82651gs/h82651gs.000051' z=19.83 t=0.18 Gyr>
[  3] 2020-02-12 17:09:01,570 : Gathering BH info from simulation for step <TimeStep u'h82651gs/h82651gs.000057' z=18.42 t=0.20 Gyr>
[  2] 2020-02-12 17:09:01,723 : Gathering existing BH halo information from database for step <TimeStep u'h82651gs/h82651gs.000054' z=19.09 t=0.19 Gyr>
[  2] 2020-02-12 17:09:01,729 : ...found 0 existing BHs
[  2] 2020-02-12 17:09:01,729 : Gathering BH info from simulation for step <TimeStep u'h82651gs/h82651gs.000054' z=19.09 t=0.19 Gyr>
[  3] 2020-02-12 17:12:16,441 : Found 6 black holes for <TimeStep u'h82651gs/h82651gs.000057' z=18.42 t=0.20 Gyr>
[  3] 2020-02-12 17:12:16,441 : Updating BH trackdata and BH objects using on-disk information from <TimeStep u'h82651gs/h82651gs.000057' z=18.42 t=0.20 Gyr>
[  3] 2020-02-12 17:12:18,819 : Committed 6 new trackdata and 6 new BH objects for <TimeStep u'h82651gs/h82651gs.000057' z=18.42 t=0.20 Gyr>
[  3] 2020-02-12 17:12:19,003 : Calculating halo associations for BHs in timestep <TimeStep u'h82651gs/h82651gs.000057' z=18.42 t=0.20 Gyr>
[  1] 2020-02-12 17:12:37,742 : Found 1 black holes for <TimeStep u'h82651gs/h82651gs.000051' z=19.83 t=0.18 Gyr>
[  1] 2020-02-12 17:12:37,742 : Updating BH trackdata and BH objects using on-disk information from <TimeStep u'h82651gs/h82651gs.000051' z=19.83 t=0.18 Gyr>
[  1] 2020-02-12 17:12:39,937 : Committed 0 new trackdata and 1 new BH objects for <TimeStep u'h82651gs/h82651gs.000051' z=19.83 t=0.18 Gyr>
[  1] 2020-02-12 17:12:39,942 : Calculating halo associations for BHs in timestep <TimeStep u'h82651gs/h82651gs.000051' z=19.83 t=0.18 Gyr>
Traceback (most recent call last):
  File "/home/u14266/.local/bin/tangos_add_bh", line 11, in <module>
    sys.exit(main())
  File "/home/u14266/.local/lib/python2.7/site-packages/tangos/scripts/add_bh.py", line 336, in main
    parallel_tasks.launch(run)
  File "/home/u14266/.local/lib/python2.7/site-packages/tangos/parallel_tasks/__init__.py", line 54, in launch
    backend.launch(_exec_function_or_server, num_procs, [function, args])
  File "/home/u14266/.local/lib/python2.7/site-packages/tangos/parallel_tasks/backends/mpi4py.py", line 61, in launch
    function(*args)
  File "/home/u14266/.local/lib/python2.7/site-packages/tangos/parallel_tasks/__init__.py", line 86, in _exec_function_or_server
    function(*args)
  File "/home/u14266/.local/lib/python2.7/site-packages/tangos/scripts/add_bh.py", line 330, in run
    scan_for_BHs(files, session)
  File "/home/u14266/.local/lib/python2.7/site-packages/tangos/scripts/add_bh.py", line 119, in scan_for_BHs
    bh_halos = bh_halos[bh_order_by_mass]
TypeError: 'NoneType' object has no attribute '__getitem__'

and the script command was:
ibrun tangos_add_bh --sims h82651gs --backend mpi4py

Let me know if you need the simulation/amiga files.

Also note my pull request.  With that pull request I was able to complete the add_bh script for the simulation.

**Comment by apontzen** [comment]
Thanks Tom - I agree the pull request looks fine, I'd just ideally like to add a regression test to the suite. I'll see if the log contains clues for a reproducible test.

**Comment by apontzen** [comment]
I have merged the fix as I don't have time to develop a regression test right now. It would be good to add one later if we possibly can.
