### ISSUE TITLE
add_bh crashes when using Grp files

### ISSUE THREAD

**Issue by mtremmel** [pynbody/tangos#118]
when using the grp files there will be no distinction between Central and non-Central BHs (halos only contain particles that are not in sub-halos). So, the bh_halo_assign function will return None for bh_halo, which will throw an error on line 119 in add_bh.py

**Comment by apontzen** [comment]
Seems to me like these .amiga.grp and .amiga.stat files are causing us a lot of problems. Why are we still using them? Perhaps we should just ensure that the AHF files are used in preference wherever possible.

**Comment by mtremmel** [comment]
I've already made a pull request. it is a simple check that should be in there anyway really.

However, you are preaching to the choir here. Still, in this instance there is an argument to be made in favor of being more general. We cannot ensure that a halo finder (or more specifically whatever input_handler used by the user) will be inclusive of sub halo particles. In fact, as it is right now, if the halo catalog is not either AHF or Rockster, this error will occur.

**Comment by mtremmel** [comment]
I've made a pull request btw to fix this. I don't have permission to link this with this issue though... (at least I don't think I do) (pull #119)

**Comment by mtremmel** [comment]
Sorry it seems there is already an (old) pull request for this made by tom (#114)

**Comment by apontzen** [comment]
OK! I will merge that. I think I was worried there was an underlying deeper issue, but now I understand what it is it makes esnse.
