### ISSUE TITLE
restarting a tangos write slower than first run

### ISSUE THREAD

**Issue by trquinn** [pynbody/tangos#121]
I'm doing a "tangos write shrink_center max_radius SFR_histogram --include-only="NDM()>1000" 
--for h82651gs" on a zoom group run, and it got killed by the job scheduler because it ran out of queue time.
I then reran, hoping that it would pick up where it left off, but found out that just as much time, if not slightly more is taken if the properties already exist.  How can I get the later timesteps processed in this simulation?

Also, I'm getting a lot of messages of the form:
/home/u14266/.local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py:129: SAWarning: This declarative base already contains a class with the same class name and module name as tangos.relation_finding.multi_hop.MultiHopHaloLink_vndj, and will be replaced in the string-lookup table.
Is this a problem?

**Comment by apontzen** [comment]
Thanks Tom. Could you attach the full logs from both runs (the original and the restart?)

**Comment by trquinn** [comment]
Here are the files.  Both are run for 12 hours with 3 MPI tasks.
[slurm-34708289.out.txt](https://github.com/pynbody/tangos/files/4950172/slurm-34708289.out.txt)
[slurm-34720048.out.txt](https://github.com/pynbody/tangos/files/4950176/slurm-34720048.out.txt)

**Comment by apontzen** [comment]
The problem is definitely to do with the `SAWarning` you are seeing. When restarting, tangos just checks through every step to see what has been written. Normally this is pretty quick, so it effectively just resumes from where it left off. However in your case it is going very slowly, taking up to several hours per step which is crazy. I assume this is something to do with the duplicate tables it is encountering, but am also puzzled about why it is creating those tables in the first place -- it suggests it's doing a very complicated search across multiple timesteps.

Is the database file on a cluster I can access?

**Comment by apontzen** [comment]
PS for a quick fix, you could run backwards, `tangos write shrink_center max_radius SFR_histogram --include-only="NDM()>1000" --for h82651gs --backwards` which will start at low redshift and work towards high redshift. Probably this will sort out the practical issue, and hopefully meet in the middle. But I'd like to get to the bottom of the actual problem too.

**Comment by trquinn** [comment]
I already discovered the backwards option, so I managed to get this done.
The database is on SDSC comet.  I can move it elsewhere if you want.

**Comment by apontzen** [comment]
I can access magneto, if you can put it there. It would also be helpful to know the exact versions of python, tangos, and sqlalchemy that you are using on SDSC comet.

**Comment by trquinn** [comment]
The data base is in magento:/local/tmp/trq/tangos/sqlite.db
```
module list
Currently Loaded Modulefiles:
  1) gnu/7.2.0          3) mkl/2018.1.163
  2) openmpi_ib/3.1.4   4) python/2.7.15
```
From site-packages:
tangos: tangos-1.0.10-py2.7.egg
sqlalchemy: SQLAlchemy-1.3.13.dist-info

**Comment by apontzen** [comment]
Thanks Tom, I believe I have now tracked down and fixed this issue in branch `issue-121` -- could you check and confirm?
