### ISSUE TITLE
trouble loading in user defined properties

### ISSUE THREAD

**Issue by mtremmel** [pynbody/tangos#15]
I just updated my TANGOS version and now for some reason it does not seem to be reading my custom properties folder. As far as I can tell it is attempting to import it, but then when I attempt a live calculation that is defined in this folder, I get that the property has no providing class. 

I did notice that a change in config.py in defining `gathering property_modules` fails to get `tangos_nbodyshop_properties`. Once I reverted back to the old way it was fine (currently the issue is with the following line... there is no "tangos_nbodyshop_properties" to get from the environment)

`property_modules = os.environ.get("TANGOS_PROPERTY_MODULES","tangos_nbodyshop_properties")`  (line 35)

Still, I find that my live properties are not found, despite the following line being called without an `ImportError` in `properties/__init__.py`

`importlib.import_module(pm)` (line 461)

I double checked that, in fact, it is attempting to import the right names to apparently no errors. Confused as to what is happening. I have checked and my folder is being compiled with the rest of tangos and exists in my library.

**Comment by mtremmel** [comment]
Ah ok so it ends up that importing both my folder as well as the nbodyshop folder failed, but the warning was not given... (I put in a print statement after the `except ImportError`. I haven't changed any paths and I've installed (after updating) the `tangos_nbodyshop_properties` repository.

**Comment by mtremmel** [comment]
Ok I think there is just a slew of issues with the properties organization being different. Will track it down and close this once I have it working for sure.

**Comment by mtremmel** [comment]
Ok once I work through the new bugs everything seems to work ok. possibly worth keeping this issue open given that the warning message for failed imports does not seem to be working?

**Comment by apontzen** [comment]
Ah damn, you may need to derive from PynbodyHaloProperties instead of HaloProperties. It became necessary to distinguish which properties work with which readers...

**Comment by mtremmel** [comment]
Yes the issue was things like spherical_region and centered_calculation are all in pynbody. There was also a random issue with my BH scripts due to the fact that requires_particle_data is no longer a function... I see there was an attempt to overcome this deprecated implementation, but it failed with an error that said that `requires_particle_data() must be called with BH instance as first argument (got nothing instead)`. Anyway I think I caught everything. Will push an update to nbodyshop scripts soon (still working on updating all the property names, but that won't actually cause an import failure)
