### ISSUE TITLE
progenitor tracking is failing for BHs

### ISSUE THREAD

**Issue by mtremmel** [pynbody/tangos#172]
BHs in the Romulus database are no longer being tracked correctly with the latest TANGOS version. Things like `previous` and `next` work fine but `earliest` returns None, `calculate_for_progenitors` returns empty arrays. Similarly, timechunked properties also fail to reassemble.

I will try to figure this out in a couple weeks when I have time again, unless someone wants to look into this in the meantime.

**Comment by apontzen** [comment]
Whoops, my bad Michael! Could you check whether this fixes it:
https://github.com/pynbody/tangos/pull/173
