### ISSUE TITLE
TANGOS currently requires pynbody

### ISSUE THREAD

**Issue by mtremmel** [pynbody/tangos#2]
the tutorial states that it is agnostic in terms of what one wishes to use (yt, pynbody,etc) but the profiles module in properties imports pynbody. So, importing the database fails if pynbody is not installed

**Comment by apontzen** [comment]
@mtremmel could you confirm PR #4 fixes this?

**Comment by mtremmel** [comment]
Yes I uninstalled pynbody and was still able to import tangos fine
