### ISSUE TITLE
Failure import_dependencies

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#20]
From a fresh install, I tried to run the tests to find errors in the import/include tests namely:

sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string '/Users/mrey/Science//tangos_data.db'

The default config.py adds /Science/ for mac systems which does not exists in my case.
Editing my own config solved the problem but the default should check for existence before adding the path.

**Comment by apontzen** [comment]
It shouldn't do this at all, actually, it's a throwback to when only I used it...

**Comment by Martin-Rey** [comment]
Agreed. Probably better to get ride of it.

**Comment by apontzen** [comment]
Did you mean to close the issue?

**Comment by Martin-Rey** [comment]
Sorry, misclicked.

BTW, the tutorial proposes to run the tests before setting up the environment variables. Shouldn't it be done the other way around ?

**Comment by apontzen** [comment]
The tutorial is correct: it's fine to run the tests without any environment variables set as it creates temporary databases within the test folders.

**Comment by Martin-Rey** [comment]
Somehow, running the tests creates a tangos_database.db file in my HOME directory (I have not set the env variables).

Getting ride of the file and rerunning the tests recreates it.

**Comment by Martin-Rey** [comment]
Fixed by PR #29
