### ISSUE TITLE
Halo #1 in HOP+Ramses

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#23]
When importing the tutorial_ramses (and one of my own ramses simulation), halo #1 in the database is always every unbound particle of the simulation. It is obviously the most massive object in the simulation.

Is there an option to specify this behaviour and avoid this ?

**Comment by apontzen** [comment]
This is a bug that was introduced by confusion in surrey... I will reverse it shortly

**Comment by apontzen** [comment]
This should now be fixed

**Comment by Martin-Rey** [comment]
I can confirm it is gone for me. 

Many thanks !
