### ISSUE TITLE
Check_delete and hanging references

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#25]
I often get this message in the log :
check_deleted failed
gc reports hanging references: [(<SimSnap "/Users/mrey/Documents/simulations/tutorial_changa_blackholes/pioneer50h128.1536gst1.bwK1BH.000640" len=32962208>,), <cell at 0x10b1c0678: TipsySnap object at 0x10c256be0>]

- Is this worrying in term of memory usage ? Does this point to a misuse on my part ?

- In the case of tipsy, the reference is one line but in the case of HOP/Ramses, the print statement is the entire description of the pynbody Subsnap, leading to massive outputs (attached for only one halo) :
[screen shot 2018-01-30 at 10 22 50](https://user-images.githubusercontent.com/22526234/35561235-92ba9f68-05a7-11e8-88f4-d195f83143d8.png)

**Comment by apontzen** [comment]
This is just python's garbage collection being garbage. There's not much we can do, but it's sometimes helpful to know it's going on.

However the big outputs do sound annoying and that should be fixed.

**Comment by apontzen** [comment]
That said could you give me the exact command line you are using? It is a bit surprising to see it come up all the time like this.

**Comment by Martin-Rey** [comment]
For the large outputs (I was getting them with the tutorial as well as my own simulations):
mpirun -np 7 tangos write dm_density_profile --with-prerequisites --include-only="contamination_fraction <0.01" --for zoom_run --backend mpi4py

For the tipsy hanging refs
mpirun -np 7 tangos_add_bh --for tutorial_changa_blackholes --backend mpi4py

**Comment by Martin-Rey** [comment]
I do not see any hanging refs with the same two commands so can't check if spurious output is fully fixed.

I'll let you know if it reappears, in the mean time, it looks fixed on my side.
