### ISSUE TITLE
Pseudo language, mpi and "&"

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#28]
I often run into an annoying problem when running more complex --include-only with mpi. For example:
`mpirun -np 6 tangos write dm_density_profile  --with-prerequisites  --for zoom_halo740 --backend mpi4py --include-only="contamination_fraction<0.01 & NDM()>500"`

produces:
usage: tangos [-h] [--db-filename database_file.sqlite3] [--db-verbose]
              [--verbose]
              {add,recent-runs,rm,flag-duplicates,remove-duplicates,import,rollback,dump-iord,list-possible-properties,write,link,crosslink,serve}
              ...
tangos: error: unrecognized arguments: & NDM()>500

This error goes away if running the command without mpi as 
`tangos write dm_density_profile  --with-prerequisites  --for zoom_halo740 --include-only="contamination_fraction<0.01 & NDM()>500"`

or if getting ride of the spaces between the two conditions as :
`--include-only="contamination_fraction<0.01&NDM()>500"`

Somehow, the mini language does not link the two conditions in the case of the first mpi command, resulting at the second being passed as an overall tangos argument.

The error also occurred when building the changa tutorial.

Are you meant to never use spaces for conditions like this ? is this a misuse on my part ?

**Comment by apontzen** [comment]
That's an issue with your shell. I believe you can probably escape the & (using \&), or use single quotes ' in place of the double quotes?
