### ISSUE TITLE
Crosslinking simulations with different number of timesteps

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#30]
I am trying to crosslink two simulations that do not have the same time sampling. This is currently allowed by tangos.

The calculation fails because in the case that sim2 has 100 snapshots against 50 for sim1, the lines
https://github.com/pynbody/tangos/blob/0054bbe409564d8b2d49d2da16b8cff8cd448cd5/tangos/tools/crosslink.py#L150-L152

assumes that handler 2 can read snapshot 100 in sim1 which rightfully throws:
'OSError: File '/Users/mrey/Documents/sim1/output_00100': format not understood or does not exist'

If the cross linking tools was not designed to work with unequal number fo snapshots, a check at the beginning of the calculation would do.

**Comment by Martin-Rey** [comment]
What is the expected behaviour of crosslink if the two sims do not have the same number of timesteps ?
a) Do not even start and raise an exception ? 
b) Or do all possible timesteps and some of them will not have a match ?

The previously described error is not captured in the current tests (though dummy_sim1 and dummy_sim2 have different timesteps) because the lines:
https://github.com/pynbody/tangos/blob/0054bbe409564d8b2d49d2da16b8cff8cd448cd5/tangos/tools/crosslink.py#L222-L229
will swallow any problems as long as it is sim1 and ts1s that have the longest length but no the other way around.

I have a fix for both a) and b). Let me know what you think and if anything is unclear.

**Comment by apontzen** [comment]
I think (b) is fine if it is clear which timestep should be matched to which other timestep, and which timesteps to ignore.

**Comment by Martin-Rey** [comment]
I can't reproduce this error anymore, neither with the tests or with my simulations. I'll close this issue for now and reopen it if I hit it again. 

Is that fine with you ?

**Comment by apontzen** [comment]
Strange! I suggest we leave this open for now as the behaviour has not been properly defined in this scenario and I certainly did not (intentionally) fix it. Once properly defined we should add tests to ensure it really does what we think it should.

**Comment by Martin-Rey** [comment]
I can confirm the error was due to the bug in PR #34. 

The default behaviour of tangos is to discard extra timesteps with no mutual pairing. This case is actually tested for in 
https://github.com/pynbody/tangos/blob/e53d5771d5c42fcad4c8904688da6ee1c40d03e8/tests/test_linking.py#L28

as the dummy simulations have different number of timesteps.
