### ISSUE TITLE
Unable to populate AHF properties

### ISSUE THREAD

**Issue by RaySSharma** [pynbody/tangos#37]
When trying to import AHF properties to a dark matter only Romulus database using
`tangos_import_from_ahf [property]`
Tangos spits out lines saying that it processes each timestep in order, but no properties are written to the database. 

Recent-runs does not recognize tangos_import_from_ahf was run. It does recognize when tangos link and tangos write are run.

AHF files exist in the directory for each timestep, and are all populated. When running:
`tangos add [simulation]`
Tangos spits out that the AHFCatalogue was loaded, so it presumably is able to read in the AHF files.

Running the same commands for tutorial_changa correctly loads in AHF properties.

The DMO database was created using the --quicker flag.
@emapple

**Comment by apontzen** [comment]
I can only guess this must be a difference in format between the tutorial example and the DMO catalogues you are trying to import. Can you identify the difference?

**Comment by apontzen** [comment]
For reference, this was a problem not with a specific format but with backwards compatibility with existing/old databases.

**Comment by emapple** [comment]
I'm not sure if this is a related issue -

I pulled the most recent version of tangos from github, and ran

` tangos import-properties Mvir --for [simulation]`
for the same situation described above.

It processed ~half of the timesteps in order, but then failed with the following traceback

> Traceback (most recent call last):
>   File "/u/eappleba/anaconda2/bin/tangos", line 11, in <module>
>     load_entry_point('tangos', 'console_scripts', 'tangos')()
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/scripts/__init__.py", line 49, in main
>     args.func(args)
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/tools/__init__.py", line 54, in run
>     parallel_tasks.launch(obj.run_calculation_loop, 2, [])
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/parallel_tasks/__init__.py", line 56, in launch
>     function(*args)
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/tools/property_importer.py", line 45, in run_calculation_loop
>     hsf.HaloStatFile(ts).add_halo_properties(*names)
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/input_handlers/halo_stat_files/__init__.py", line 159, in add_halo_properties
>     property_objects.append(tangos.core.halo_data.HaloProperty(halo, name_object, value))
>   File "<string>", line 4, in __init__
>   File "/u/eappleba/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
>     manager.dispatch.init_failure(self, args, kwargs)
>   File "/u/eappleba/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/u/eappleba/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
>     return manager.original_init(*mixed[1:], **kwargs)
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/core/halo_data/property.py", line 40, in __init__
>     self.data = data
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/core/halo_data/property.py", line 91, in data
>     data_attribute_mapper.set_data_of_unknown_type(self, data)
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/core/data_attribute_mapper.py", line 30, in set_data_of_unknown_type
>     mapper.set(obj,data)
>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/core/data_attribute_mapper.py", line 107, in set
>     raise TypeError("%r object does not have a slot for %r"%(type(db_object),self._attribute_name))
> 
> TypeError: <class 'tangos.core.halo_data.property.HaloProperty'> object does not have a slot for 'data_string'

**Comment by emapple** [comment]
Using #50 I received the same error -- from here in the traceback

>   File "/nobackupp2/eappleba/romulus.dmo/tangos/tangos/input_handlers/halo_stat_files/__init__.py", line 160, in add_halo_properties
    property_objects.append(tangos.core.halo_data.HaloProperty(halo, name_object, value))

it appears that line 159 of the file evaluated true
` if isinstance(value, float) or isinstance(value, str):`

**Comment by apontzen** [comment]
Oops, my typo - please try again

**Comment by emapple** [comment]
Thanks! It worked, and said some variant of

> Ignoring stat file entry key='Mvir' value='3e+08' as the value is not a number

for every time step that otherwise would have failed, where value was int+e10 or similar. I'm assuming this is an int/float issue?

**Comment by apontzen** [comment]
Sounds like it, I tried adding an extra fix that should pick up these values correctly, give it a go!

**Comment by apontzen** [comment]
@emapple just a ping to see if this now works?

**Comment by emapple** [comment]
@apontzen Seems to work! No more hitches on my end.
