### ISSUE TITLE
Unable to connect to tangos within web browser

### ISSUE THREAD

**Issue by Morkney** [pynbody/tangos#40]
When trying to open the tangos web browser with the command 
`tangos serve`
the browser loads to a page which simply reads 'unable to connect' or 'problem loading page'.

The TANGOS_DB_CONNECTION path is set correctly, I am keeping the terminal open whilst trying to access the web browser, and all the functionality works from Python, but I am unable to open the web browser.

The text returned by the serve command is as follows:
```
Starting server in PID 12992.
Serving on http://localhost:6543
Serving on http://localhost:6543
```

**Comment by apontzen** [comment]
It all looks correct so I am unclear why your browser might be failing to connect. Is the server and browser definitely running on the same machine, or are you SSHing? If so, are you sure the SSH tunnelling is correctly configured?
