### ISSUE TITLE
tangos won't recognise new property module

### ISSUE THREAD

**Issue by milchada** [pynbody/tangos#61]
I am trying to add a custom property to (a local copy of) a database. The code lives here:
https://github.com/milchada/tangos_properties_uchadaya/
The property of interest is described in vdisp.py. iPython successfully imports this module. We added the following to tangos/properties/__init__.py:
```
def _import_configured_property_modules():
    from ..config import property_modules
    for pm in property_modules:
        if pm=="": continue
        print(pm)
```
So tangos prints the names of the modules it tries to import, i.e. TANGOS_PROPERTY_MODULES. It prints my module name.
However, when I ask for the property class of the property I have defined, I get:
`NameError: No providing class for property v_disp_profile`
This error regardless of which directory I try the import from. 

What am I missing?

**Comment by apontzen** [comment]
Thanks for reporting! This does sound strange and I can’t immediately understand what the problem would be.

Could you report the full result of `tangos list-possible-properties`? And how exactly are you asking for the property class from the name, could you give the exact code?

**Comment by milchada** [comment]
Hi Andrew! Here it is:
```
tangos list-possible-properties
tangos_properties_uchadaya
                          name |     handler     | property class
-------------------------------+-----------------+-------------------------------------------------------------
           BH_central_distance | PynbodyInputHan | tangos.properties.pynbody.BH.BH
...
                v_disp_profile | PynbodyInputHan | tangos_properties_uchadaya.vdisp.VDispProfile
                             z |       live      | tangos.properties.intrinsic.IntrinsicProperties
```
v_disp_profile is the property I defined.
I check for the property class in iPython as follows:
```
import tangos
tangos.properties.providing_class('v_disp_profile')
```
Here is the batch script I use to add the property to the database:
```
#PBS -S /bin/bash
#PBS -N db-RC
#PBS -l select=2:ncpus=24:mpiprocs=1:model=bro:bigmem=False
#PBS -l walltime=2:00:00
#PBS -q devel

cd $PBS_O_WORKDIR
module load mpi-sgi/mpt
export TANGOS_PROPERTY_MODULES=tangos_nbodyshop_properties, tangos_properties_uchadaya
export TANGOS_SIMULATION_FOLDER=/nobackupp2/mtremmel/Romulus/
export TANGOS_DB_CONNECTION=/nobackupp2/uchadaya/data_romulusC.db
export SIMS="h1.cosmo50"

mpiexec tangos write v_disp_profile --for $SIMS --type halo --load-mode=server --backend mpi4py --backwards --hmax 1

```

**Comment by apontzen** [comment]
OK, so tangos is definitely picking up your module and registering the class, which is good.

The reason `tangos.properties.providing_class('v_disp_profile')` is because, as the list states, your class is only compatible with pynbody. You have to tell it you'll be providing pynbody data so `tangos.properties.providing_class('v_disp_profile', tangos.input_handlers.pynbody.PynbodyInputHandler)`. The docstring states that, without specifying this, you'll only see live properties.

If your batch script is failing, though, I'm less sure what's going wrong - maybe send a pointer to the output?

**Comment by milchada** [comment]
Ah, I see - specifying the handler did help iPython access the providing class. 
The batch job error file is attached.
[db-RC.e3960409.txt](https://github.com/pynbody/tangos/files/2074163/db-RC.e3960409.txt)

**Comment by apontzen** [comment]
Really weird. Could you try inserting `tangos list-possible-properties` into the batch script and checking what comes out just to be sure it is picking up in that environment too. 

Also, what is `tangos.get_simulation("<simulation name>").get_output_handler()`?

**Comment by milchada** [comment]
Aha! list-possible-properties in the batch script does **not** list properties from my module. 
Given the submission script above, why would this be the case if iPython knows where to look?

PS The output handler is fine in ipython:
`<tangos.input_handlers.pynbody.ChangaInputHandler at 0x7fffc1735c10>`

**Comment by apontzen** [comment]
Hard to know - could it be that somehow your PYTHONPATH is incorrect within PBS, so the module import fails? 

That should trigger a warning but maybe somehow it is not showing up.

Maybe try printing something in your module `__init.py__` to test if it's being imported in the batch runs?

**Comment by apontzen** [comment]
Sorry, dropped the ball on this one. I find this really, really weird. Could there somehow be a different `PYTHONPATH` in the batch environment compared to your normal shell?

**Comment by milchada** [comment]
Wow, it turns out the issue is that I specified:
`export TANGOS_PROPERTY_MODULES=tangos_nbodyshop_properties, tangos_properties_uchadaya`
and that space bar between the module names was the problem! when i removed it, tangos_list_properties shows my property as well.

**Comment by apontzen** [comment]
Yes, this is not an issue with tangos but rather with parsing in the shell. An alternative way around it is to `export TANGOS_PROPERTY_MODULES="tangos_nbodyshop_properties, tangos_properties_uchadaya"` - the quotes will stop the space from interfering.

Closing the issue now.
