### ISSUE TITLE
Stars go missing in halo properties

### ISSUE THREAD

**Issue by Morkney** [pynbody/tangos#68]
I've made a custom Tangos property which makes calculations involving the stars of a halo from a Ramses simulation. I set up the property like:

```
class HaloProperty(SphericalRegionHaloProperties):
    @centred_calculation
    def calculate(self, halo, existing_properties):
```

Up until now this has worked as expected, and calling 'halo.s' returns a dataset containing the star particles. However, in a recent simulation things have changed. Up until output 31 it works as normal, but afterwards it doesn't seem to find any stars.

If I load the simulation into Pynbody and centre on the desired halo then I find plenty of stars.
What could cause Tangos to miss these star particles?

**Comment by apontzen** [comment]
Weird! Can you point me at the specific outputs?

**Comment by Morkney** [comment]
Hi!
The outputs are located on dial under /data/dp101/dc-ager1/
Outputs 42 and up seem to cause a problem.

I've been experimenting a little more and other halo properties also seem to be very strange. A value calculated in Tangos is different than one calculated in Pynbody despite the fact that the arguments are identical and the halos are the same. It seems to suggest the centring is different, although the "shrink_center" property matches the Pynbody centering perfectly.

**Comment by apontzen** [comment]
I'm afraid I can't reproduce any error. Can you be specific about what values are differing?

Is it possible that one of your property calculations is failing to "put the data back" when it's finished, leading to incorrect values later? 

If you need further help, please point to the database you have calculated with the problems, all output logs, and the property modules you are using.

**Comment by Morkney** [comment]
Hello again,

There was a single 'nan' in one of the simulation outputs which was causing a cascade of other problems. I think it was responsible for all of the problems!
