### ISSUE TITLE
Tangos cannot load output 

### ISSUE THREAD

**Issue by Morkney** [pynbody/tangos#71]
Hello,

I've tried producing Tangos databases for some star-forming RAMSES simulations, only I am getting the "Could not load /sim_path/output_#####" error when I run this command:

`tangos add simulation --min-particles 1000 --no-renumber`

I've not met this error on previous simulations using the exact same Tangos distribution, so I think the problem is that either the RAMSES or HOP outputs are using some long-integers rather than standard integers. Would this cause this sort of problem?

**Comment by Martin-Rey** [comment]
Have you tried loading one of the snapshot and its halo catalogue directly with pynbody?

Something like:
s = pynbody.load('/sim_path/output_#####')
h = s.halos()

**Comment by Morkney** [comment]
I have tried, and it produces this error:

RuntimeError: Mismatching number of particles between snapshot Halo####/output_##### and HOP file /sim_path/Halo####/grp#####.tag

**Comment by Martin-Rey** [comment]
Ok so this is a HOP loading issue rather than a tangos problem. The error comes from this check in Pynbody:
https://github.com/pynbody/pynbody/blob/c7e4c273521c87907e8af62b3b04f258e4e39806/pynbody/halo/hop.py#L36

My gut instinct is that  HOP number of particles include stars, which then fails against len(simulation.dm). Could you confirm or exclude this?

**Comment by apontzen** [comment]
I've taken a look at this and think it's a residual bug/incompatibility in HOP. The GenetIC DM particles can take iord=0, so line 521 of `hop_input.c` should be updated to

```C
if(temp_dbl[j]==0.) ncurr=ncurr+1;
```

and similarly line 640 should be updated to

```C
if(a_dbl[j]==0.) {
```

(i.e. in both cases remove the condition on the `temp_id`)

I don't think anything in pynbody or tangos needs to change... but give it a go and see!

**Comment by Morkney** [comment]
After making the changes suggested by @apontzen, the HOP files load into Pynbody as per usual. I expect they will work in Tangos too. Thank you for the help!

**Comment by Morkney** [comment]
Hello again,

I've reopened this issue because I have just noticed another problem which I am convinced is related to this one. If I try running tangos link on any simulation run using GenetIC then 0 links are found and no merger history is built. 

An example terminal output looks like this: 

```
2018-09-27 09:52:24,982 : Gathering links for <TimeStep u'Halo1445/output_00008' z=13.27 t=0.32 Gyr> and <TimeStep u'Halo1445/output_00009' z=11.50 t=0.39 Gyr>
2018-09-27 09:52:24,982 : Identified 0 links between <TimeStep u'Halo1445/output_00008' z=13.27 t=0.32 Gyr> and <TimeStep u'Halo1445/output_00009' z=11.50 t=0.39 Gyr>
2018-09-27 09:52:24,982 : Identified 0 links between <TimeStep u'Halo1445/output_00009' z=11.50 t=0.39 Gyr> and <TimeStep u'Halo1445/output_00008' z=13.27 t=0.32 Gyr>
2018-09-27 09:52:24,982 : Preparing to commit links for <TimeStep u'Halo1445/output_00008' z=13.27 t=0.32 Gyr> and <TimeStep u'Halo1445/output_00009' z=11.50 t=0.39 Gyr>
2018-09-27 09:52:24,985 : Finished committing total of 0 links for <TimeStep u'Halo1445/output_00008' z=13.27 t=0.32 Gyr> and <TimeStep u'Halo1445/output_00009' z=11.50 t=0.39 Gyr>
```

No errors are thrown up, which is why I didn't immediately notice this problem.

**Comment by apontzen** [comment]
I don’t think this is directly related - please open a new issue.
