### ISSUE TITLE
--force and --with-prerequisites

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#73]
Hi,

I am seeing an unexpected behaviour when running the following command:
`mpirun -np 8 tangos write dm_density_profile
--load-mode=server --with-prerequisites --for my_simulation --backend mpi4py`

The calculation does not seem to check if prerequisites or the calculated property already exist in the database. It recalculates and store all the properties again as if using the `--force` keyword. I was not seeing this behaviour with the same command before updating my tangos architecture.

Is this a change of behaviour or a bug?
Martin

**Comment by apontzen** [comment]
Sounds like a bug to me

**Comment by Martin-Rey** [comment]
It does fix it! I have tried both running with --prerequisites flag and without. I only have a super minor comment on PR #74. 

I assume this issue was introduced in commit 4d83f1f395ae596e60d9a97ab503f8077f7fc302

Thanks for sorting this out.
