### ISSUE TITLE
Tangos write for a halo and its progenitors

### ISSUE THREAD

**Issue by Morkney** [pynbody/tangos#76]
Hello,

Currently 'Tangos write' allows the option to calculate properties for specific halo numbers. This is useful for when I only want to calculate properties for a single main halo, as it saves time and avoids making the database file unnecessarily large.

If I used the argument --hmax=0 then I would only create properties for the largest halo, which would be exactly what I want except that the main halo in a simulation may not be the largest halo at very early time steps.

Is there a way to calculate halo properties for a specific halo based on the results of 'Tangos link' instead? IE, I would only have properties for the halo that is halo_0 at the final output and all of its progenitor halos.

EDIT:
I've tried altering the property_writer.py file in Tangos, but I don't know enough about how the code works to effect the changes I want. Ideally I would run something similar to this:

```
        if self.options.hmax is not None:
            query = sqlalchemy.and_(query, core.halo.Halo.halo_number<=self.options.hmax)
```

Instead of halo_number, I would be sorting by the halo_number of a linked halo. Instead of hmax, I would have an argument 'hlink' which would be the halo number at z=0. I've found the properties Halo.next, Halo.previous, Halo.links, etc etc. However, they don't return an integer which can be used in the sqlalchemy query. I've tried to change the source code such that they do, but to no avail.

After finding the appropriate halo, I would then update the hlink argument so that it assumed the value of the current halo halo_number. Again, I've no idea how to actually do this in Tangos. Assuming Tangos writer is run in time order, this would then build up the properties for all the progenitors of Halo_0. 

EDIT 2:
I'm currently using a workaround, where I manually paste the results of  `halo.calculate_for_progenitors("halo_number()")` into an argument in Tangos write. This isn't very pretty but it does what I need.

**Comment by apontzen** [comment]
Sorry for the delayed response. Does something like `tangos write .... --include-only="earliest().halo_number()<2"` work?

**Comment by Martin-Rey** [comment]
I can confirm the solution works. 

If one wants a specific halo (e.g. halo 4), one can do:
`tangos write ... include-only="latest().halo_number()<5" --include-only="latest().halo_number()>3"`

**Comment by apontzen** [comment]
I added the obvious `==` feature in PR#81, so that you can do

```
tangos write ... --include-only="latest().halo_number()==4"
```

**Comment by Martin-Rey** [comment]
Sounds great! Thanks a lot
