### ISSUE TITLE
Pynbody handler always crosslinks with itself

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#77]
Hi, 
I am running again in an issue fixed by https://github.com/pynbody/tangos/commit/239c5223a9d71b9c0fd20975e5180c81375967c6: crosslinking two simulations always map halo 12 of simulation1/timestep5 with halo 12 of simulation2/timestep5, i.e. linking with itself and not taking into account particle ids.

I believe this bug was introduced following commit https://github.com/pynbody/tangos/commit/50bd7c06453242faaf38ab85440f53d7e66084f7:
- This line checks whether some snapshots are stored in memory, based on the timestep extension.
https://github.com/pynbody/tangos/blob/854edc7df661970dbbd0a2f2000d9b8de170ba2e/tangos/input_handlers/__init__.py#L117-L118

- In the case of crosslinking the **extension** of simulation1/timestep5 and simulation2/timestep5 are actually the same, for example "output_0005" in my case. 

- Rather than loading simulation2/timestep5, the handler then reuses the memory stored simulation1/timestep5, hence ending up linking with itself.

The easiest is probably for the hash to check with _extension_to_filename() rather than just extension but I don't want to break what you tried to achieve with these commits.

Let me know what you think!

**Comment by apontzen** [comment]
Yes, I agree it should be hashing the full filename rather than the extension. Are you able to submit a PR for this?

**Comment by Martin-Rey** [comment]
Thanks for the fix and the test!
