### ISSUE TITLE
eagle branch fails to recognize existing properties

### ISSUE THREAD

**Issue by mtremmel** [pynbody/tangos#82]
I'm currently using the eagle branch as there are some optimizations for gathering existing properties. However, this seems to make it so that TANGOS no longer recognizes when an asked-for property already exists and calculates it anyway (I did not force the calculation)

**Comment by apontzen** [comment]
I think this is a duplicate of #73

**Comment by mtremmel** [comment]
yes it totally is! Sorry about that!
