### ISSUE TITLE
Contamination fraction is inconsistent between load-modes

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#85]
Hi all,

I noticed today that the result of the calculation "contamination_fraction" is inconsistent between being done with different load-modes.

Currently, "contamination_fraction" looks into the loaded particles, find the minimum mass of those and calculate the fraction of particles more massive than this minimum mass. 

1) In a load-mode in which the entire snapshot is loaded, the minimum mass is always the overall minimum mass in the simulation (zoom resolution) so the calculation returns 1.0 for unzoomed halo, 0.X for contaminated halos and 0.0 for uncontaminated zoomed halos.

2) In a load-mode in which only halo data is loaded (e.g. server), the minimum mass is calculated locally, not necessarily knowing that there exists a zoom region elsewhere in the simulation. For example, a pure unzoomed halo will have minimum_mass 64 and zero particles above this value, while a pure zoomed halo will have minimum_mass 8.0 and zero particles above. The calculation then returns 0.0 for unzoomed halos, 0.X for contaminated halos and 0.0 for uncontaminated zoomed halos.

I am not sure which one should be the correct behaviour (number 1 for me) but the fact that it is inconsistent between load-mode is highly confusing.

Hope this is clear
Martin

**Comment by apontzen** [comment]
Yes the problem is clear but I am not immediately sure how to solve it actually. Any bright ideas?

**Comment by apontzen** [comment]
Yes, I guess that would work. If you implement it, would be good to have it transparent in the sense that the code will "do its best" if the appropriate value is not stored at the simulation level.

**Comment by Martin-Rey** [comment]
Fixed by #91
